aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:oss-cn-shenzhen.aliyuncs.com}
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID:}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:}
    bucket-name: ${ALIYUN_OSS_BUCKET_NAME:bookkeeping-by-hugo}
    url-prefix: ${ALIYUN_OSS_URL_PREFIX:}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookkeeping
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8080

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0  # 逻辑未删除值

wechat:
  miniapp:
    appid: ${WECHAT_MINIAPP_APPID:}  # 你的小程序 AppID
    secret: ${WECHAT_MINIAPP_SECRET:} # 你的小程序 AppSecret
